update the two shell script to use getopts and parse flags rather than positional argument input

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -1,6 +1,36 @@
 #!/usr/bin/env bash
-METRICS_SERVER=${1:-0}
-if [ "$METRICS_SERVER" -eq 1 ]; then
+set -e
+
+function_setup_help() {
+  echo "
+Command: setup
+Usage:
+  setup [flags]
+
+Synopsis:
+  setup [-mh]
+
+Flags:
+  -m    Install the metric server
+  -h    Help, which is what you looking at now"
+  exit 1
+}
+
+while getopts ":mh" opt; do
+  case $opt in
+  m)
+    METRICS_SERVER=true
+    ;;
+  h)
+    function_setup_help
+    ;;
+  \?)
+    echo "Invalid option -$OPTARG" >&2
+    ;;
+  esac
+done
+
+if [ "$METRICS_SERVER" = true ]; then
   echo "Installing the metrics server"
   ### we need the metrics server to do commands like kubectl top pods and activate hpa
   helm install metrics-server stable/metrics-server -f monitoring/metrics-server-values.yaml -n kube-system
diff --git a/teardown b/teardown
--- a/teardown
+++ b/teardown
@@ -1,5 +1,39 @@
 #!/usr/bin/env bash
-FULL_TEARDOWN=${1:-0}
+set -e
+
+function_teradown_help() {
+  echo "
+Command: teardown
+Usage:
+  teardown [flags]
+
+Synopsis:
+  setup [-mfh]
+
+Options:
+  -m    Uninstall the metric server
+  -f    Full teardown including the namespace
+  -h    Help, which is what you looking at now"
+  exit 1
+}
+
+while getopts ":fmh" opt; do
+  case $opt in
+  f)
+    FULL_TEARDOWN=true
+    ;;
+  m)
+    METRICS_SERVER=true
+    ;;
+  h)
+    function_teradown_help
+    ;;
+  \?)
+    echo "Invalid option -$OPTARG" >&2
+    ;;
+  esac
+done
+
 echo "Deleting the components in the logging namespace"
 
 helm delete elasticsearch fluent-bit kibana -n logging
@@ -13,7 +47,7 @@ kubectl delete -f monitoring/grafana-configs.yaml -n monitoring
 echo "Deleting the components in the ingress namespace"
 helm delete nginx -n ingress
 
-if [ "$FULL_TEARDOWN" -eq 1 ]; then
+if [ "$FULL_TEARDOWN" = true ]; then
   echo "Deleting the namespaces"
   kubectl delete -f logging/namespace.yaml
   kubectl delete -f monitoring/namespace.yaml
@@ -21,4 +55,10 @@ if [ "$FULL_TEARDOWN" -eq 1 ]; then
 
   echo "Deleting the metrics server"
   helm delete metrics-server -n kube-system
+elif [ "$METRICS_SERVER" = true ]; then
+  echo "Deleting the metrics server"
+  helm delete metrics-server -n kube-system
 fi
+
+
+
